# Generated by Django 5.0.6 on 2024-06-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approver2', models.TextField(max_length=100)),
                ('approver3', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=100)),
                ('mail', models.TextField(blank=True, max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('work', models.TextField(blank=True, max_length=500)),
                ('worktype', models.TextField(blank=True, max_length=20)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prof_name', models.TextField(blank=True, max_length=100)),
                ('prof_mail', models.TextField(blank=True, max_length=100)),
                ('approval1', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('May be', 'May be')], default='Pending', max_length=10)),
                ('approval2', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('May be', 'May be')], default='Pending', max_length=10)),
                ('approval3', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('May be', 'May be')], default='Pending', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('remarks1', models.TextField(blank=True, max_length=1000)),
                ('remarks2', models.TextField(blank=True, max_length=1000)),
                ('remarks3', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('status_text', models.TextField(blank=True, max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
