# Generated by Django 5.0.6 on 2024-08-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remarks1',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remarks2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='remarks3',
        ),
    ]
