# Generated by Django 5.0.6 on 2024-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_remarks1_order_remarks_remove_order_remarks2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
