# Generated by Django 5.0.6 on 2024-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_expected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Workdone', 'Workdone'), ('Inprogress', 'Inprogress')], default='Inprogress', max_length=10),
        ),
    ]
