# Generated by Django 5.0.6 on 2024-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_completed_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Workdone', 'Workdone'), ('Inprogress', 'Inprogress'), ('Cantbedone', 'Cantbedone')], default='Inprogress', max_length=10),
        ),
    ]
